ibp_ex:
  delta_threshold: 0.5
  epsilon: 0.1
  k: 0.12
  lr: 0.02
  num_epochs: 30
  restarts: 4
  weight_coeff: 0.008
ibp_ex+r3:
  delta_threshold: 0.5
  epsilon: 0.1
  k: 0.2
  lr: 0.02
  num_epochs: 20
  restarts: 4
  weight_coeff: 0.006
pgd_r4:
  delta_threshold: 0.5
  epsilon: 0.1
  k: 0.7
  lr: 0.03
  num_epochs: 30
  restarts: 4
  weight_coeff: 0.0005
pgd_r4_pmo:
  delta_threshold: 0.5
  epsilon: 0.3
  k: 0.7
  lr: 0.025
  num_epochs: 35
  restarts: 4
  weight_coeff: 0.0006
r3:
  delta_threshold: 0.5
  epsilon: 0.1
  k: 0.05
  lr: 0.01
  num_epochs: 20
  restarts: 4
  weight_coeff: 0.006
r4:
  delta_threshold: 0.5
  epsilon: 0.1
  k: 1
  lr: 0.02
  num_epochs: 25
  restarts: 4
  weight_coeff: -1
r4_pmo:
  delta_threshold: 0.5
  epsilon: 0.3
  k: 20
  lr: 0.01
  num_epochs: 25
  restarts: 4
  weight_coeff: -1
rand_r4:
  delta_threshold: 0.5
  epsilon: 0.1
  k: 20
  lr: 0.02
  num_epochs: 30
  restarts: 4
  weight_coeff: 0.0001
rand_r4_pmo:
  delta_threshold: 0.5
  epsilon: 0.3
  k: 20
  lr: 0.02
  num_epochs: 30
  restarts: 4
  weight_coeff: 0.0001
smooth_r3:
  delta_threshold: 0.5
  epsilon: 0.1
  k: 50000.0
  lr: 0.01
  num_epochs: 30
  restarts: 4
  weight_coeff: 1.0e-08
std:
  delta_threshold: 0.5
  epsilon: 0.1
  k: 0.2
  lr: 0.01
  num_epochs: 30
  restarts: 4
  weight_coeff: 0.01
