ibp_ex:
  class_weights: -1
  epsilon: 0.25
  has_conv: false
  k: 4
  lr: 0.075
  multi_class: true
  num_epochs: 30
  restarts: 4
  test_batch_size: 1000
  test_epsilon: 0.1
  train_batch_size: 1000
  weight_coeff: 0.0002
  with_k_schedule: false
ibp_ex+r3:
  class_weights: -1
  epsilon: 0.15
  has_conv: false
  k: 2.1
  lr: 0.01
  multi_class: true
  num_epochs: 30
  restarts: 4
  test_batch_size: 1000
  test_epsilon: 0.1
  train_batch_size: 1000
  weight_coeff: 0.0006
  with_k_schedule: false
pgd_r4:
  class_weights: -1
  epsilon: 0.5
  has_conv: false
  k: 14
  lr: 0.001
  multi_class: true
  num_epochs: 30
  restarts: 4
  test_batch_size: 1000
  test_epsilon: 0.1
  train_batch_size: 1000
  weight_coeff: 0.0001
  with_k_schedule: false
r3:
  class_weights: -1
  epsilon: 0.1
  has_conv: false
  k: 10
  lr: 0.025
  multi_class: true
  num_epochs: 25
  restarts: 4
  test_batch_size: 1000
  test_epsilon: 0.1
  train_batch_size: 1000
  weight_coeff: 0.0001
  with_k_schedule: false
r4:
  class_weights: -1
  epsilon: 0.5
  has_conv: false
  k: 15
  lr: 0.001
  multi_class: true
  num_epochs: 25
  restarts: 4
  test_batch_size: 1000
  test_epsilon: 0.1
  train_batch_size: 1000
  weight_coeff: -1
  with_k_schedule: false
rand_r4:
  class_weights: -1
  epsilon: 0.5
  has_conv: false
  k: 15
  lr: 0.001
  multi_class: true
  num_epochs: 30
  restarts: 4
  test_batch_size: 1000
  test_epsilon: 0.1
  train_batch_size: 1000
  weight_coeff: 0.0001
  with_k_schedule: false
smooth_r3:
  class_weights: -1
  epsilon: 0.1
  has_conv: false
  k: 10
  lr: 0.001
  multi_class: true
  num_epochs: 25
  restarts: 4
  test_batch_size: 1000
  test_epsilon: 0.1
  train_batch_size: 1000
  weight_coeff: 0.0001
  with_k_schedule: false
std:
  class_weights: -1
  epsilon: 0.1
  has_conv: false
  k: -1
  lr: 0.01
  multi_class: true
  num_epochs: 30
  restarts: 4
  test_batch_size: 1000
  test_epsilon: 0.1
  train_batch_size: 1000
  weight_coeff: -1
  with_k_schedule: false
