ibp_ex:
  class_weights:
  - 1.5
  - !!python/object/apply:torch._utils._rebuild_tensor_v2
    - !!python/object/apply:torch.storage._load_from_bytes
      - !!binary |
        gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
        AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
        aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
        Z2UKcQFYDgAAADk5NDc2NTU1NzA1MTIwcQJYAwAAAGNwdXEDSwFOdHEEUS6AAl1xAFgOAAAAOTk0
        NzY1NTU3MDUxMjBxAWEuAQAAAAAAAADTvQFA
    - 0
    - !!python/tuple []
    - !!python/tuple []
    - false
    - !!python/object/apply:collections.OrderedDict
      - []
  epsilon: 0.05
  has_conv: true
  k: 0.005
  lr: 1.0e-05
  multi_class: false
  num_epochs: 10
  restarts: 3
  test_batch_size: 256
  test_epsilon: 0.01
  train_batch_size: 256
  weight_decay: 1.0e-05
  with_k_schedule: false
ibp_ex+r3:
  class_weights:
  - 0.9
  - !!python/object/apply:torch._utils._rebuild_tensor_v2
    - !!python/object/apply:torch.storage._load_from_bytes
      - !!binary |
        gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
        AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
        aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
        Z2UKcQFYDgAAADk5NDc2NTU4NDE1ODQwcQJYAwAAAGNwdXEDSwFOdHEEUS6AAl1xAFgOAAAAOTk0
        NzY1NTg0MTU4NDBxAWEuAQAAAAAAAADTvQFA
    - 0
    - !!python/tuple []
    - !!python/tuple []
    - false
    - !!python/object/apply:collections.OrderedDict
      - []
  epsilon: 0.05
  has_conv: true
  k: 0.005
  lr: 1.0e-05
  multi_class: false
  num_epochs: 11
  restarts: 3
  test_batch_size: 256
  test_epsilon: 0.01
  train_batch_size: 256
  weight_decay: 3.0e-05
  with_k_schedule: false
r3:
  class_weights:
  - 1
  - !!python/object/apply:torch._utils._rebuild_tensor_v2
    - !!python/object/apply:torch.storage._load_from_bytes
      - !!binary |
        gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
        AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
        aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
        Z2UKcQFYDgAAADk5NDc2NTUwNjU5NzQ0cQJYAwAAAGNwdXEDSwFOdHEEUS6AAl1xAFgOAAAAOTk0
        NzY1NTA2NTk3NDRxAWEuAQAAAAAAAADTvQFA
    - 0
    - !!python/tuple []
    - !!python/tuple []
    - false
    - !!python/object/apply:collections.OrderedDict
      - []
  epsilon: 0.01
  has_conv: true
  k: 1000
  lr: 5.0e-06
  multi_class: false
  num_epochs: 15
  restarts: 3
  test_batch_size: 256
  test_epsilon: 0.01
  train_batch_size: 256
  weight_decay: 0.0001
  with_k_schedule: false
r4:
  class_weights:
  - 1
  - !!python/object/apply:torch._utils._rebuild_tensor_v2
    - !!python/object/apply:torch.storage._load_from_bytes
      - !!binary |
        gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
        AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
        aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
        Z2UKcQFYDgAAADk5NDc2NTUzOTU4MjQwcQJYAwAAAGNwdXEDSwFOdHEEUS6AAl1xAFgOAAAAOTk0
        NzY1NTM5NTgyNDBxAWEuAQAAAAAAAADTvQFA
    - 0
    - !!python/tuple []
    - !!python/tuple []
    - false
    - !!python/object/apply:collections.OrderedDict
      - []
  epsilon: 0.05
  has_conv: true
  k: 1
  lr: 0.0003
  multi_class: false
  num_epochs: 25
  restarts: 3
  test_batch_size: 256
  test_epsilon: 0.01
  train_batch_size: 256
  weight_decay: 2.0e-05
  with_k_schedule: false
std:
  class_weights:
  - 1
  - !!python/object/apply:torch._utils._rebuild_tensor_v2
    - !!python/object/apply:torch.storage._load_from_bytes
      - !!binary |
        gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
        AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
        aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
        Z2UKcQFYDgAAADk5NDc3NDE5MzcyNTc2cQJYAwAAAGNwdXEDSwFOdHEEUS6AAl1xAFgOAAAAOTk0
        Nzc0MTkzNzI1NzZxAWEuAQAAAAAAAADTvQFA
    - 0
    - !!python/tuple []
    - !!python/tuple []
    - false
    - !!python/object/apply:collections.OrderedDict
      - []
  epsilon: 0.01
  has_conv: true
  k: -1
  lr: 0.0001
  multi_class: false
  num_epochs: 12
  restarts: 3
  test_batch_size: 256
  test_epsilon: 0.01
  train_batch_size: 256
  weight_coeff: -1
  with_k_schedule: false
