ibp_ex:
  class_weights:
  - 1.5
  - 2.0272
  epsilon: 0.05
  has_conv: true
  k: 0.005
  lr: 1.0e-05
  multi_class: false
  num_epochs: 10
  restarts: 3
  test_batch_size: 256
  test_epsilon: 0.01
  train_batch_size: 256
  weight_decay: 1.0e-05
  with_k_schedule: false
ibp_ex+r3:
  class_weights:
  - 0.9
  - 2.0272
  epsilon: 0.05
  has_conv: true
  k: 0.005
  lr: 1.0e-05
  multi_class: false
  num_epochs: 11
  restarts: 3
  test_batch_size: 256
  test_epsilon: 0.01
  train_batch_size: 256
  weight_decay: 3.0e-05
  with_k_schedule: false
pgd_r4:
  class_weights:
  - 0.85
  - 2.0272
  epsilon: 0.05
  has_conv: true
  k: 10
  lr: 2.0e-05
  multi_class: false
  num_epochs: 6
  restarts: 3
  test_batch_size: 256
  test_epsilon: 0.01
  train_batch_size: 256
  weight_decay: 7.0e-05
  with_k_schedule: false
r3:
  class_weights:
  - 1.3
  - 2.0272
  epsilon: 0.01
  has_conv: true
  k: 1000
  lr: 2.0e-06
  multi_class: false
  num_epochs: 24
  restarts: 3
  test_batch_size: 256
  test_epsilon: 0.01
  train_batch_size: 256
  weight_decay: 1.0e-08
  with_k_schedule: false
r4:
  class_weights:
  - 1.07
  - 2.0272
  epsilon: 0.05
  has_conv: true
  k: 1
  lr: 0.0003
  multi_class: false
  num_epochs: 30
  restarts: 3
  test_batch_size: 256
  test_epsilon: 0.01
  train_batch_size: 256
  weight_decay: 2.0e-05
  with_k_schedule: false
rand_r4:
  class_weights:
  - 0.9
  - 2.0272
  epsilon: 0.05
  has_conv: true
  k: 2000
  lr: 1.0e-05
  multi_class: false
  num_epochs: 11
  restarts: 3
  test_batch_size: 256
  test_epsilon: 0.01
  train_batch_size: 256
  weight_decay: 2.0e-05
  with_k_schedule: false
smooth_r3:
  class_weights:
  - 1
  - 2.0272
  epsilon: 0.05
  has_conv: true
  k: 1000
  lr: 1.0e-05
  multi_class: false
  num_epochs: 10
  restarts: 3
  test_batch_size: 256
  test_epsilon: 0.01
  train_batch_size: 256
  weight_decay: 2.0e-05
  with_k_schedule: false
std:
  class_weights:
  - 1
  - 2.0272
  epsilon: 0.01
  has_conv: true
  k: -1
  lr: 0.0001
  multi_class: false
  num_epochs: 12
  restarts: 3
  test_batch_size: 256
  test_epsilon: 0.01
  train_batch_size: 256
  weight_coeff: -1
  with_k_schedule: false
