ibp_ex:
  delta_threshold: 1
  epsilon: 0.05
  k: 0.6
  lr: 0.001
  num_epochs: 10
  restarts: 4
  weight_coeff: 0.0002
ibp_ex+r3:
  delta_threshold: 1
  epsilon: 0.05
  k: 0.5
  lr: 0.001
  num_epochs: 10
  restarts: 4
  weight_coeff: 0.0002
r3:
  delta_threshold: 1
  epsilon: 0.05
  k: 0.04
  lr: 0.0001
  num_epochs: 12
  restarts: 4
  weight_coeff: 0.001
r4:
  delta_threshold: 1
  epsilon: 0.05
  k: 0.05
  lr: 0.0003
  num_epochs: 12
  restarts: 4
  weight_coeff: -1
std:
  delta_threshold: 1
  epsilon: 0.1
  k: -1
  lr: 0.001
  num_epochs: 10
  restarts: 4
  weight_coeff: -1
