pgd_r4:
  epsilon: 0.01
  k: 0.6
  lr: 0.0001
  num_epochs: 8
  restarts: 3
  weight_coeff: 1.0e-05
pgd_r4_pmo:
  epsilon: 0.03
  k: 1
  lr: 0.0001
  num_epochs: 8
  restarts: 3
  weight_coeff: 1.0e-05
rand_r4_pmo:
  delta_threshold: 1
  epsilon: 0.03
  k: 200000.0
  lr: 8.0e-05
  num_epochs: 7
  restarts: 3
  weight_coeff: 0
smooth_r3:
  epsilon: 0.01
  k: 400
  lr: 8.0e-05
  num_epochs: 10
  restarts: 3
  weight_coeff: 1.0e-06
std:
  epsilon: -1
  k: -1
  lr: 0.0001
  num_epochs: 5
  restarts: 1
  weight_coeff: -1
