r3:
  delta_threshold: 1
  epsilon: 0.01
  k: 0.08
  lr: 0.0004
  num_epochs: 12
  restarts: 3
  weight_coeff: 0.0001
r4:
  delta_threshold: 1
  epsilon: 0.01
  k: 0.01
  lr: 0.0005
  num_epochs: 14
  restarts: 3
  weight_coeff: -1
std:
  epsilon: 0.1
  k: -1
  lr: 0.0002
  num_epochs: 2
  restarts: 1
  weight_coeff: -1
