pgd_r4:
  class_weights: null
  epsilon: 0.5
  has_conv: true
  k: 0.1
  lr: 5.0e-05
  multi_class: true
  num_epochs: 30
  restarts: 1
  seed: 22
  test_batch_size: 33
  test_epsilon: 0.5
  train_batch_size: 33
  weight_decay: 0
  with_k_schedule: false
r3:
  class_weights: null
  epsilon: 0
  has_conv: true
  k: 100
  lr: 4.0e-05
  multi_class: true
  num_epochs: 32
  restarts: 1
  seed: 1
  test_batch_size: 33
  test_epsilon: 0
  train_batch_size: 33
  weight_decay: 1.0e-05
  with_k_schedule: false
rand_r4:
  class_weights: null
  epsilon: 1
  has_conv: true
  k: 10000
  lr: 5.0e-05
  multi_class: true
  num_epochs: 25
  num_samples: 5
  restarts: 1
  seed: 22
  test_batch_size: 33
  test_epsilon: 1
  train_batch_size: 33
  weight_decay: 1.0e-07
  with_k_schedule: false
smooth_r3:
  class_weights: null
  epsilon: 0.75
  has_conv: true
  k: 100
  lr: 6.0e-05
  multi_class: true
  num_epochs: 20
  num_samples: 5
  restarts: 1
  seed: 1
  test_batch_size: 33
  test_epsilon: 0.75
  train_batch_size: 33
  weight_decay: 1.0e-05
  with_k_schedule: false
std:
  class_weights: null
  epsilon: -1
  has_conv: true
  k: -1
  lr: 0.0001
  multi_class: true
  num_epochs: 20
  restarts: 1
  test_batch_size: 33
  test_epsilon: -1
  train_batch_size: 33
  weight_coeff: -1
  with_k_schedule: false
