r3:
  delta_threshold: 1
  epsilon: 0.01
  k: 0.08
  lr: 0.0004
  num_epochs: 12
  restarts: 3
  weight_coeff: 0.0001
std:
  delta_threshold: 1
  epsilon: 0.1
  k: 0.2
  lr: 0.0002
  num_epochs: 12
  restarts: 3
  weight_coeff: -1
