pgd_r4:
  alpha: 0.2
  class_weights: -1
  k: 500000000000.0
  lr: 2.5e-06
  multi_class: false
  num_epochs: 1
  restarts: 1
  test_batch_size: 80
  train_batch_size: 80
  weight_decay: 1.0e-05
pgd_r4_0:
  alpha: 0.1
  class_weights: -1
  k: 100000000000.0
  lr: 1.0e-06
  multi_class: false
  num_epochs: 1
  restarts: 1
  test_batch_size: 80
  train_batch_size: 80
  weight_decay: 1.0e-05
pgd_r4_2:
  alpha: 0.15
  class_weights:
  - 1
  - 1.7
  k: 600000000000.0
  lr: 2.0e-06
  multi_class: false
  num_epochs: 1
  restarts: 1
  test_batch_size: 80
  train_batch_size: 80
  weight_decay: 1.0e-05
pgd_r4_3:
  alpha: 0.15
  class_weights:
  - 1
  - 1.6
  k: 670000000000.0
  lr: 1.5e-06
  multi_class: false
  num_epochs: 1
  restarts: 1
  test_batch_size: 80
  train_batch_size: 80
  weight_decay: 1.0e-05
pgd_r4_4:
  alpha: 0.15
  class_weights:
  - 1
  - 1.55
  k: 710000000000.0
  lr: 2.0e-06
  multi_class: false
  num_epochs: 1
  restarts: 1
  test_batch_size: 80
  train_batch_size: 80
  weight_decay: 1.0e-05
pgd_r4_5:
  alpha: 0.15
  class_weights:
  - 1
  - 1.45
  k: 790000000000.0
  lr: 2.0e-06
  multi_class: false
  num_epochs: 1
  restarts: 1
  test_batch_size: 80
  train_batch_size: 80
  weight_decay: 1.0e-05
pgd_r4_6:
  alpha: 0.15
  class_weights:
  - 1
  - 1.5
  k: 750000000000.0
  lr: 2.0e-06
  multi_class: false
  num_epochs: 1
  restarts: 1
  test_batch_size: 80
  train_batch_size: 80
  weight_decay: 1.0e-05
r3:
  class_weights: -1
  k: 4000000000000.0
  lr: 1.0e-05
  multi_class: false
  num_epochs: 2
  restarts: 1
  test_batch_size: 52
  train_batch_size: 52
  weight_decay: 1.0e-05
rand_r4:
  alpha: 0.5
  class_weights:
  - 1
  - 1.55
  k: 800000000000.0
  lr: 1.0e-05
  multi_class: false
  num_epochs: 1
  num_samples: 3
  restarts: 1
  test_batch_size: 66
  train_batch_size: 66
  weight_decay: 1.0e-05
rand_r4_best:
  alpha: 0.5
  class_weights:
  - 1
  - 1.7
  k: 600000000000.0
  lr: 1.0e-05
  multi_class: false
  num_epochs: 1
  num_samples: 3
  restarts: 1
  test_batch_size: 77
  train_batch_size: 77
  weight_decay: 1.0e-05
smooth_r3:
  alpha: 0.25
  class_weights:
  - 1
  - 1.7
  k: 4500000000000.0
  lr: 1.0e-05
  multi_class: false
  num_epochs: 1
  num_samples: 3
  restarts: 1
  test_batch_size: 88
  train_batch_size: 88
  weight_decay: 1.0e-05
std:
  class_weights: -1
  k: 0
  lr: 0.0001
  multi_class: false
  num_epochs: 2
  restarts: 1
  test_batch_size: 50
  train_batch_size: 50
  weight_decay: 0
