r3:
  class_weights: -1
  k: 4000000000000.0
  lr: 1.0e-05
  multi_class: false
  num_epochs: 2
  restarts: 1
  test_batch_size: 52
  train_batch_size: 52
  weight_decay: 1.0e-05
rand_r4:
  alpha: 0.5
  class_weights:
  - 1
  - 1.7
  k: 600000000000.0
  lr: 1.0e-05
  multi_class: false
  num_epochs: 1
  num_samples: 3
  restarts: 1
  test_batch_size: 77
  train_batch_size: 77
  weight_decay: 1.0e-05
rand_r4_best:
  alpha: 0.75
  class_weights:
  - 1
  - 1.7
  k: 700000000000.0
  lr: 1.0e-05
  multi_class: false
  num_epochs: 1
  num_samples: 3
  restarts: 1
  test_batch_size: 77
  train_batch_size: 77
  weight_decay: 1.0e-05
smooth_r3:
  alpha: 0.25
  class_weights:
  - 1
  - 1.7
  k: 4500000000000.0
  lr: 1.0e-05
  multi_class: false
  num_epochs: 1
  num_samples: 3
  restarts: 1
  test_batch_size: 88
  train_batch_size: 88
  weight_decay: 1.0e-05
std:
  class_weights: -1
  k: 0
  lr: 0.0001
  multi_class: false
  num_epochs: 2
  restarts: 1
  test_batch_size: 50
  train_batch_size: 50
  weight_decay: 0
