ibp_ex:
  class_weights:
  - 1.9
  - 1
  epsilon: 0.01
  has_conv: true
  k: 0.01
  lr: 0.0001
  multi_class: false
  num_epochs: 18
  restarts: 3
  test_batch_size: 50
  test_epsilon: 0.01
  train_batch_size: 50
  weight_coeff: 5.0e-05
  with_k_schedule: false
ibp_ex+r3:
  class_weights:
  - 1.85
  - 1
  epsilon: 0.01
  has_conv: true
  k: 0.01
  lr: 8.0e-05
  multi_class: false
  num_epochs: 20
  restarts: 3
  test_batch_size: 50
  test_epsilon: 0.01
  train_batch_size: 50
  weight_decay: 5.0e-05
  with_k_schedule: false
pgd_r4:
  class_weights:
  - 2.3
  - 1
  epsilon: 0.03
  has_conv: true
  k: 0.003
  lr: 5.0e-05
  multi_class: false
  num_epochs: 15
  restarts: 1
  test_batch_size: 50
  test_epsilon: 0.01
  train_batch_size: 50
  weight_coeff: 5.0e-05
  with_k_schedule: false
r3:
  class_weights:
  - 4.5
  - 1
  epsilon: 0.01
  has_conv: true
  k: 25
  lr: 0.0001
  multi_class: false
  num_epochs: 20
  restarts: 3
  test_batch_size: 50
  test_epsilon: 0.01
  train_batch_size: 50
  weight_coeff: 5.0e-05
  with_k_schedule: false
r4:
  alpha_soft: 0.7
  class_weights:
  - 2.3
  - 1
  epsilon: 0.02
  has_conv: true
  k: 0.01
  lr: 0.0002
  multi_class: false
  num_epochs: 12
  restarts: 1
  test_batch_size: 50
  test_epsilon: 0.01
  train_batch_size: 50
  weight_coeff: -1
  with_k_schedule: false
rand_r4:
  class_weights:
  - 2.1
  - 1
  epsilon: 0.025
  has_conv: true
  k: 0.05
  lr: 5.0e-05
  multi_class: false
  num_epochs: 21
  num_samples: 3
  restarts: 3
  test_batch_size: 50
  test_epsilon: 0.01
  train_batch_size: 50
  weight_coeff: 0.0003
  with_k_schedule: false
smooth_r3:
  class_weights:
  - 2.4
  - 1
  epsilon: 0.01
  has_conv: true
  k: 0.01
  lr: 7.0e-05
  multi_class: false
  num_epochs: 17
  num_samples: 3
  restarts: 3
  test_batch_size: 50
  test_epsilon: 0.01
  train_batch_size: 50
  weight_coeff: 0.0001
  with_k_schedule: false
std:
  class_weights:
  - 2.5
  - 1
  epsilon: 0.01
  has_conv: true
  k: -1
  lr: 0.0001
  multi_class: false
  num_epochs: 12
  restarts: 3
  test_batch_size: 50
  test_epsilon: 0.01
  train_batch_size: 50
  weight_coeff: -1
  with_k_schedule: false
