ibp_ex:
  alpha_soft: 0.3
  delta_threshold: 1
  epsilon: 0.01
  k: 0.4
  lr: 0.0002
  num_epochs: 10
  restarts: 3
  weight_coeff: 0.003
ibp_ex+r3:
  alpha_soft: 0.35
  delta_threshold: 1
  epsilon: 0.01
  k: 0.12
  lr: 0.0005
  num_epochs: 12
  restarts: 3
  weight_coeff: 0.002
r3:
  delta_threshold: 1
  epsilon: 0.01
  k: 0.03
  lr: 0.0003
  num_epochs: 10
  restarts: 3
  weight_coeff: 0.004
r4:
  alpha_soft: 0.45
  delta_threshold: 1
  epsilon: 0.01
  k: 0.03
  lr: 0.0004
  num_epochs: 14
  restarts: 3
  weight_coeff: -1
std:
  delta_threshold: 1
  epsilon: 0.1
  k: 0.2
  lr: 0.001
  num_epochs: 7
  restarts: 3
  weight_coeff: -1
