ibp_ex:
  delta_threshold: 1
  epsilon: 0.01
  k: 0.05
  lr: 0.0005
  num_epochs: 8
  restarts: 3
  weight_coeff: 0.0001
ibp_ex+r3:
  delta_threshold: 1
  epsilon: 0.01
  k: 0.07
  lr: 0.0005
  num_epochs: 8
  restarts: 3
  weight_coeff: 0.0001
r3:
  delta_threshold: 1
  epsilon: 0.01
  k: 0.04
  lr: 0.001
  num_epochs: 8
  restarts: 3
  weight_coeff: 0.0001
r4:
  alpha_soft: 0.5
  delta_threshold: 1
  epsilon: 0.01
  k: 0.01
  lr: 0.0004
  num_epochs: 10
  restarts: 3
  weight_coeff: -1
std:
  delta_threshold: 1
  epsilon: 0.1
  k: 0.2
  lr: 0.001
  num_epochs: 7
  restarts: 3
  weight_coeff: -1
