ibp_ex:
  alpha_soft: 0.2
  delta_threshold: 1
  epsilon: 0.01
  k: 0.05
  lr: 0.0005
  num_epochs: 8
  restarts: 3
  weight_coeff: 0.0001
ibp_ex+r3:
  delta_threshold: 1
  epsilon: 0.01
  k: 0.07
  lr: 0.0005
  num_epochs: 8
  restarts: 3
  weight_coeff: 0.0001
r3:
  delta_threshold: 1
  epsilon: 0.01
  k: 0.03
  lr: 0.0003
  num_epochs: 10
  restarts: 3
  weight_coeff: 0.004
r4:
  alpha_soft: 0.6
  delta_threshold: 1
  epsilon: 0.01
  k: 0.02
  lr: 0.0005
  num_epochs: 20
  restarts: 3
  weight_coeff: -1
std:
  delta_threshold: 1
  epsilon: 0.1
  k: 0.2
  lr: 0.001
  num_epochs: 7
  restarts: 3
  weight_coeff: -1
