pgd_r4:
  alpha: 0.3
  class_weights: -1
  k: 50000000000.0
  lr: 5.0e-05
  multi_class: false
  num_epochs: 1
  restarts: 1
  test_batch_size: 88
  train_batch_size: 88
  weight_decay: 0
r3:
  class_weights: -1
  k: 5000000000.0
  lr: 2.5e-05
  multi_class: false
  num_epochs: 2
  restarts: 1
  test_batch_size: 64
  train_batch_size: 64
  weight_decay: 0
rand_r4:
  alpha: 0.75
  class_weights: -1
  k: 10000000000.0
  lr: 2.5e-05
  multi_class: false
  num_epochs: 2
  num_samples: 3
  restarts: 1
  test_batch_size: 66
  train_batch_size: 66
  weight_decay: 0
smooth_r3:
  alpha: 0.1
  class_weights: -1
  k: 1000000000.0
  lr: 5.0e-05
  multi_class: false
  num_epochs: 2
  num_samples: 3
  restarts: 1
  test_batch_size: 66
  train_batch_size: 66
  weight_decay: 0
std:
  class_weights: -1
  k: 0
  lr: 0.0001
  multi_class: false
  num_epochs: 2
  restarts: 1
  test_batch_size: 64
  train_batch_size: 64
  weight_decay: 0
