pgd_r4:
  alpha: 0.15
  class_weights:
  - 1.35
  - 1
  k: 710000000000.0
  lr: 2.0e-06
  multi_class: false
  num_epochs: 1
  num_frags: 4
  restarts: 2
  test_batch_size: 250
  train_batch_size: 80
  weight_decay: 1.0e-05
r3:
  class_weights:
  - 1.3
  - 1
  k: 1000000000000.0
  lr: 1.1e-06
  multi_class: false
  num_epochs: 1
  num_frags: 4
  restarts: 2
  test_batch_size: 250
  train_batch_size: 80
  weight_decay: 1.0e-05
rand_r4:
  alpha: 0.25
  class_weights:
  - 1.35
  - 1
  k: 800000000000.0
  lr: 2.0e-06
  multi_class: false
  num_epochs: 1
  num_frags: 11
  num_samples: 3
  restarts: 2
  test_batch_size: 250
  train_batch_size: 88
  weight_decay: 0
smooth_r3:
  alpha: 0.25
  class_weights:
  - 1.3
  - 1
  k: 1000000000000.0
  lr: 1.2e-06
  multi_class: false
  num_epochs: 1
  num_frags: 11
  num_samples: 3
  restarts: 2
  test_batch_size: 250
  train_batch_size: 88
  weight_decay: 0
std:
  class_weights: -1
  k: 0
  lr: 0.0001
  multi_class: false
  num_epochs: 2
  restarts: 2
  test_batch_size: 60
  train_batch_size: 60
  weight_decay: 0
